name: "Test"
on:
  pull_request:
  push:
    branches:
      - master
      - staging
      - trying
jobs:
  tests:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        variants: [stable, latest, bash4]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@V28
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
          extra_nix_config: |
            experimental-features = nix-command flakes
      - run: "nix run --accept-flake-config .#test-runner-${{ matrix.variants }}"
